version: "3.9"

services:
  db:
    image: postgres
    user: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 3s
      timeout: 5s
      retries: 5
  app:
    build: .
    env_file:
      - ./dev.env
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
